default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 'Shoma-0319'  # ここにMySQLのrootパスワードを入れる（ダブルクォート必須）
  host: localhost  # 追加
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: kickscheck_development

test:
  <<: *default
  database: kickscheck_test

production:
  database: <%= ENV['DB_DATABASE'] %>
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>


